/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface ThriftCodeGenOptions {
  /**  Generated file type name, the default value is .ts. */
  extName?: string
  /** Whether to convert the data type of map in thrift to Object in js instead of Map when parsing data, the default value is false. */
  mapAsObject?: boolean
  /** Whether to convert the data type of set in thrift to Array in js instead of Set when parsing data, the default value is false. */
  setAsArray?: boolean
  /**  Whether to convert the data type of i64 in thrift to string in js instead of bigint when parsing data, the default value is false. */
  int64AsString?: boolean
  /** Whether to convert the data type of i64 in thrift to string in js instead of bigint when parsing data, the default value is false. */
  int64AsNumber?: boolean
  /** The path of the thrift file to be parsed. */
  path: string
}
export declare function gen(options: ThriftCodeGenOptions): void
